import { Button } from "@/components/ui/button";
import { ArrowRight, BarChart3, BellRing, BrainCircuit, CheckCircle2, Landmark, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { useLocation } from "wouter";

const featureCards = [
  { icon: TrendingUp, title: "Predict", text: "Estimate cost, schedule, and implementation risk from meaningful synthetic project relationships." },
  { icon: BellRing, title: "Detect", text: "Raise prioritised signals before a project is formally recorded as delayed or over-budget." },
  { icon: BrainCircuit, title: "Explain", text: "Show contributing factors, trajectory, feature values, and analytical attention areas." },
  { icon: ShieldCheck, title: "Prioritize", text: "Compare sectors, ministries, states, and agencies using transparent metrics." },
  { icon: Sparkles, title: "Simulate", text: "Test controlled what-if changes while keeping simulation outputs clearly labeled." },
  { icon: BarChart3, title: "Investigate", text: "Explore project evidence, alerts, performance, and safe query-based intelligence." },
];

export default function Home() {
  const [, setLocation] = useLocation();
  const reduceMotion = useReducedMotion() || new URLSearchParams(window.location.search).get("motion") === "reduce";
  const reveal = reduceMotion ? {} : { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.25 }, transition: { duration: 0.55, ease: "circOut" as const } };

  return (
    <div className="min-h-screen overflow-hidden bg-[#f8fafc] text-[#12324f]">
      <header className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-5 sm:px-8">
        <div className="flex shrink-0 items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-[#133d62] text-white shadow-lg shadow-[#143b62]/15"><Landmark className="size-5" /></span><div className="hidden sm:block"><p className="text-sm font-semibold tracking-tight">InfraNexus</p><p className="text-[10px] font-medium uppercase tracking-[0.14em] text-[#6f8396]">Infrastructure Intelligence</p></div></div>
        <Button variant="outline" className="shrink-0 border-[#c7d7e5] bg-white px-3 text-xs text-[#21496c] shadow-sm transition-transform duration-150 active:scale-[0.97] sm:px-4 sm:text-sm" onClick={() => setLocation("/dashboard")}><span className="sm:hidden">Open demo</span><span className="hidden sm:inline">Open workspace</span><ArrowRight className="ml-2 size-4" /></Button>
      </header>
      <main>
        <section className="relative mx-auto max-w-7xl px-5 pb-16 pt-14 sm:px-8 lg:pb-24 lg:pt-24">
          <div className="absolute -right-40 -top-16 size-[520px] rounded-full bg-[#dcebf7]/70 blur-3xl" /><div className="absolute -left-40 bottom-0 size-[400px] rounded-full bg-[#eaf1f7] blur-3xl" />
          <div className="relative grid items-center gap-12 lg:grid-cols-[1.1fr_0.9fr]">
            <motion.div {...reveal}>
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#cbdce9] bg-white px-3 py-1.5 text-[11px] font-semibold text-[#35658c]"><span className="size-1.5 rounded-full bg-emerald-500" /><Sparkles className="size-3.5" />MoSPI HACKATHON · INFRASTRUCTURE INTELLIGENCE</div>
              <h1 className="max-w-3xl text-4xl font-semibold leading-[1.08] tracking-[-0.055em] text-[#102e4a] sm:text-5xl lg:text-6xl">From monitoring infrastructure to <span className="text-[#2a6a9d]">predicting risk.</span></h1>
              <p className="mt-6 max-w-2xl text-base leading-7 text-[#5a7085]">InfraNexus turns project monitoring data into an explainable early-warning workspace for cost exposure, schedule pressure, implementation conditions, and prioritised review.</p>
              <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" className="bg-[#143e64] px-6 shadow-[0_12px_24px_rgba(20,62,100,.18)] transition-transform duration-150 active:scale-[0.97] hover:bg-[#0e3153]" onClick={() => setLocation("/dashboard")}>Explore Infrastructure Intelligence <ArrowRight className="ml-2 size-4" /></Button><Button size="lg" variant="outline" className="border-[#c6d7e6] bg-white text-[#21496c] transition-transform duration-150 active:scale-[0.97]" onClick={() => setLocation("/presentation")}>View Risk Command Center</Button></div>
              <div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs text-[#506b82]"><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4 text-emerald-600" />Predictive analytics</span><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4 text-emerald-600" />Explainable outputs</span><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4 text-emerald-600" />Controlled query layer</span></div>
            </motion.div>
            <motion.div {...(reduceMotion ? {} : { initial: { opacity: 0, scale: 0.97 }, whileInView: { opacity: 1, scale: 1 }, viewport: { once: true }, transition: { duration: 0.7, delay: 0.12, ease: "circOut" as const } })} className="relative">
              <svg viewBox="0 0 520 420" className="pointer-events-none absolute -left-12 -top-10 h-[115%] w-[115%] opacity-50" aria-hidden="true"><defs><linearGradient id="network" x1="0" x2="1"><stop stopColor="#b7d8ee" /><stop offset="1" stopColor="#4a85b3" /></linearGradient></defs><g fill="none" stroke="url(#network)" strokeWidth="1.5"><path d="M75 150C190 48 270 106 414 55" /><path d="M42 287C174 214 264 280 471 210" /><path d="M123 356C220 222 328 312 445 120" /><path d="M190 64C197 180 311 182 473 302" /></g>{[[75,150],[190,64],[270,106],[414,55],[42,287],[174,214],[264,280],[471,210],[123,356],[328,312],[445,120]].map(([x,y],index) => <circle key={index} cx={x} cy={y} r={index === 3 || index === 7 ? 7 : 4} fill={index === 3 || index === 7 ? "#d75862" : "#4a85b3"}>{!reduceMotion ? <animate attributeName="r" values={index === 3 || index === 7 ? "5;9;5" : "3;5;3"} dur={`${2.7 + index * 0.16}s`} repeatCount="indefinite" /> : null}</circle>)}</svg>
              <div className="relative rounded-2xl border border-[#d1dee9] bg-white p-5 shadow-[0_24px_70px_rgba(31,73,109,0.14)]"><div className="flex items-center justify-between border-b border-[#e6edf3] pb-4"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#648099]">Portfolio command centre</p><p className="mt-1 text-lg font-semibold">Risk posture</p></div><span className="rounded-full bg-[#eef5fb] px-2.5 py-1 text-[10px] font-semibold text-[#34648a]">Synthetic Demo</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl border border-[#e1e9f0] p-3"><p className="text-[10px] uppercase tracking-wide text-[#71859a]">Projects</p><p className="mt-1 text-2xl font-semibold tracking-tight">1,248</p><p className="mt-1 text-[10px] text-[#768899]">Demonstration portfolio</p></div><div className="rounded-xl border border-rose-100 bg-rose-50/40 p-3"><p className="text-[10px] uppercase tracking-wide text-rose-600">Priority signals</p><p className="mt-1 text-2xl font-semibold tracking-tight text-rose-700">428</p><p className="mt-1 text-[10px] text-rose-600">High / critical risk</p></div></div><div className="mt-4 rounded-xl border border-[#e1e9f0] p-4"><div className="mb-4 flex items-center justify-between"><p className="text-xs font-semibold text-[#315574]">Monthly risk trend</p><TrendingUp className="size-4 text-[#3973a1]" /></div><div className="flex h-20 items-end gap-2">{[31, 36, 38, 42, 49, 54, 59].map((height, index) => <motion.div key={index} className="flex-1 rounded-t-sm bg-[#5e90b8]" initial={reduceMotion ? false : { height: "8%" }} whileInView={{ height: `${height}%` }} viewport={{ once: true }} transition={{ duration: 0.55, delay: index * 0.06 }} style={{ opacity: 0.55 + index * 0.06 }} />)}</div><div className="mt-3 flex justify-between text-[10px] text-[#7a8b9a]"><span>Mar</span><span>Aug</span></div></div><div className="mt-4 grid grid-cols-3 gap-2">{[{ icon: BellRing, label: "Detect" }, { icon: BrainCircuit, label: "Explain" }, { icon: BarChart3, label: "Prioritize" }].map(item => <div key={item.label} className="rounded-lg bg-[#f5f8fb] p-2.5 text-center transition-transform duration-200 hover:-translate-y-0.5"><item.icon className="mx-auto size-4 text-[#4375a0]" /><p className="mt-1.5 text-[10px] font-semibold text-[#4e6981]">{item.label}</p></div>)}</div></div>
              <div className="absolute -bottom-5 -left-5 hidden rounded-xl border border-[#d7e4ee] bg-white/90 px-3 py-2 shadow-lg backdrop-blur sm:block"><p className="text-[9px] font-semibold uppercase tracking-wide text-[#8191a1]">Early warning</p><p className="mt-1 text-xs font-semibold text-rose-700">Critical signal detected</p></div><div className="absolute -right-5 top-16 hidden rounded-xl border border-[#d7e4ee] bg-white/90 px-3 py-2 shadow-lg backdrop-blur sm:block"><p className="text-[9px] font-semibold uppercase tracking-wide text-[#8191a1]">Cost overrun</p><p className="mt-1 text-xs font-semibold text-[#214d73]">78% probability</p></div>
            </motion.div>
          </div>
        </section>
        <section className="border-y border-[#e1e9ef] bg-white"><div className="mx-auto grid max-w-7xl gap-4 px-5 py-12 sm:px-8 md:grid-cols-2 lg:grid-cols-3">{featureCards.map((item, index) => <motion.div {...(reduceMotion ? {} : { initial: { opacity: 0, y: 14 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.25 }, transition: { duration: 0.42, delay: (index % 3) * 0.07 } })} key={item.title} className="rounded-xl border border-[#e5edf3] p-5 transition-all duration-200 hover:-translate-y-1 hover:border-[#c9dcec] hover:shadow-[0_16px_30px_rgba(27,67,101,.08)]"><span className="grid size-9 place-items-center rounded-lg bg-[#edf4fa] text-[#3670a0]"><item.icon className="size-4" /></span><h2 className="mt-4 text-sm font-semibold text-[#1d4668]">{item.title}</h2><p className="mt-2 text-xs leading-5 text-[#687e92]">{item.text}</p></motion.div>)}</div></section>
        <section className="mx-auto max-w-7xl px-5 py-6 sm:px-8" />
      </main>
    </div>
  );
}
