import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { MapPinned, ShieldCheck } from "lucide-react";
import { divIcon } from "leaflet";
import "leaflet/dist/leaflet.css";
import { CircleMarker, MapContainer, Marker, Rectangle, TileLayer, Tooltip as LeafletTooltip, useMapEvents } from "react-leaflet";
import MarkerClusterGroup from "react-leaflet-cluster";
import "react-leaflet-cluster/dist/assets/MarkerCluster.css";
import "react-leaflet-cluster/dist/assets/MarkerCluster.Default.css";
import { useState } from "react";

export const LEAFLET_STATE_COORDINATES: Record<string, [number, number]> = { Maharashtra: [19.076, 72.878], Gujarat: [23.023, 72.572], "Tamil Nadu": [13.083, 80.271], Karnataka: [12.972, 77.595], "Uttar Pradesh": [26.847, 80.947], Rajasthan: [26.912, 75.787], "Madhya Pradesh": [23.26, 77.413], Odisha: [20.296, 85.825], "West Bengal": [22.573, 88.364], Telangana: [17.385, 78.487], Assam: [26.144, 91.736], Kerala: [8.524, 76.936] };

type ReviewZone = { north: number; south: number; east: number; west: number };

export function LeafletProjectMap({ states, selectedState, onSelectState }: { states: string[]; selectedState: string; onSelectState: (state: string) => void }) {
  return <div className="relative h-full w-full overflow-hidden rounded-lg"><MapContainer center={[22.8, 79.5]} zoom={4.5} minZoom={4} maxZoom={8} scrollWheelZoom={false} className="h-full w-full" aria-label="Leaflet project map for geographic filtering"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{states.map(name => { const coordinates = LEAFLET_STATE_COORDINATES[name]; if (!coordinates) return null; const selected = selectedState === name; return <CircleMarker key={name} center={coordinates} radius={selected ? 11 : 8} pathOptions={{ color: "#ffffff", weight: 2, fillColor: selected ? "#143b62" : "#3271a6", fillOpacity: selected ? 1 : 0.84 }} eventHandlers={{ click: () => onSelectState(name) }}><LeafletTooltip direction="top" offset={[0, -7]} opacity={0.95}>{selected ? `${name} selected` : `Filter projects in ${name}`}</LeafletTooltip></CircleMarker>; })}</MapContainer><div className="pointer-events-none absolute bottom-7 left-3 z-[500] rounded-md border border-[#d6e1ec] bg-white/95 px-2.5 py-2 text-[10px] text-[#5c7185] shadow-sm">{selectedState === "All" ? "Click a state marker to filter projects." : <>Selected location: <b className="text-[#244c6e]">{selectedState}</b></>}</div></div>;
}

function NativeReviewZoneDrawer({ onZoneChange }: { onZoneChange: (zone: ReviewZone) => void }) {
  const [start, setStart] = useState<[number, number] | null>(null);
  useMapEvents({ click: event => { const point: [number, number] = [event.latlng.lat, event.latlng.lng]; if (!start) { setStart(point); return; } onZoneChange({ north: Math.max(start[0], point[0]), south: Math.min(start[0], point[0]), east: Math.max(start[1], point[1]), west: Math.min(start[1], point[1]) }); setStart(null); } });
  return start ? <CircleMarker center={start} radius={7} pathOptions={{ color: "#143b62", weight: 2, fillColor: "#60a5c9", fillOpacity: 0.85 }}><LeafletTooltip permanent direction="top" offset={[0, -8]}>Choose opposite corner</LeafletTooltip></CircleMarker> : null;
}

export function LeafletReviewZoneMap({ states, selectedState, onSelectState, reviewZone, onZoneChange }: { states: string[]; selectedState: string; onSelectState: (state: string) => void; reviewZone: ReviewZone | null; onZoneChange: (zone: ReviewZone | null) => void }) {
  return <div className="relative h-full w-full overflow-hidden rounded-lg"><MapContainer center={[22.8, 79.5]} zoom={4.5} minZoom={4} maxZoom={8} scrollWheelZoom={false} className="h-full w-full" aria-label="Leaflet map with custom review-zone drawing tools"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><NativeReviewZoneDrawer onZoneChange={onZoneChange} />{reviewZone ? <Rectangle bounds={[[reviewZone.south, reviewZone.west], [reviewZone.north, reviewZone.east]]} pathOptions={{ color: "#143b62", weight: 2, fillColor: "#60a5c9", fillOpacity: 0.14 }} /> : null}{states.map(name => { const coordinates = LEAFLET_STATE_COORDINATES[name]; if (!coordinates) return null; const selected = selectedState === name; return <CircleMarker key={name} center={coordinates} radius={selected ? 11 : 8} pathOptions={{ color: "#ffffff", weight: 2, fillColor: selected ? "#143b62" : "#3271a6", fillOpacity: selected ? 1 : 0.84 }} eventHandlers={{ click: () => onSelectState(name) }}><LeafletTooltip direction="top" offset={[0, -7]} opacity={0.95}>{selected ? `${name} selected` : `Filter projects in ${name}`}</LeafletTooltip></CircleMarker>; })}</MapContainer><div className="pointer-events-none absolute bottom-7 left-3 z-[500] rounded-md border border-[#d6e1ec] bg-white/95 px-2.5 py-2 text-[10px] text-[#5c7185] shadow-sm">{reviewZone ? "Custom review zone active. Click twice to replace it, or use Clear review zone." : "Click two opposite corners to define a custom review zone."}</div></div>;
}

export function LeafletDashboardMap({ points, onSelectProject }: { points: Array<{ id: string; name: string; state: string; risk: number }>; onSelectProject: (projectId: string) => void }) {
  const iconFor = (risk: number) => { const color = risk > 75 ? "#dc4c5a" : risk > 50 ? "#db882f" : risk > 25 ? "#3e9b76" : "#477da9"; const symbol = risk > 75 ? "!" : "•"; return divIcon({ className: "", html: `<span style="display:grid;place-items:center;width:24px;height:24px;border-radius:999px;border:2px solid #fff;background:${color};color:#fff;font:700 15px/1 sans-serif;box-shadow:0 2px 8px rgba(26,57,86,.28)">${symbol}</span>`, iconSize: [24, 24], iconAnchor: [12, 12] }); };
  return <MapContainer center={[22.8, 79.5]} zoom={4.2} minZoom={4} maxZoom={8} scrollWheelZoom={false} className="h-full w-full" aria-label="Leaflet dashboard map of representative project-risk locations"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><MarkerClusterGroup chunkedLoading maxClusterRadius={42} showCoverageOnHover={false}>{points.map((point, index) => { const base = LEAFLET_STATE_COORDINATES[point.state]; if (!base) return null; const offsetLat = ((index % 4) - 1.5) * 0.16; const offsetLng = ((Math.floor(index / 4) % 4) - 1.5) * 0.18; return <Marker key={point.id} position={[base[0] + offsetLat, base[1] + offsetLng]} icon={iconFor(point.risk)} eventHandlers={{ click: () => onSelectProject(point.id) }}><LeafletTooltip direction="top" offset={[0, -12]} opacity={0.95}>{`${point.name} · ${point.state} · ${point.risk}/100`}</LeafletTooltip></Marker>; })}</MarkerClusterGroup></MapContainer>;
}

function MapPanel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-[#dce4ed] bg-white shadow-[0_8px_24px_rgba(32,57,85,0.045)]"><div className="px-5 pt-5"><h2 className="text-sm font-semibold text-[#173b5f]">{title}</h2></div><div className="p-5">{children}</div></section>; }
function MapHeader() { return <><div className="paimana-page-header mb-6 flex items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-[#61738a]">Authorised spatial intelligence</p><h1 className="text-2xl font-semibold tracking-[-0.03em] text-[#102a43] md:text-3xl">Risk map</h1></div><Badge variant="outline" className="border-[#bedbd7] bg-[#f1faf8] text-[#176b67]">Coordinate safeguards active</Badge></div></>; }

export function AuthorizedRiskMap() {
  const coordinates = trpc.userWorkspace.activeAuthorizedCoordinates.useQuery(undefined, { retry: false });
  if (coordinates.isLoading) return <><MapHeader /><MapPanel title="Loading authorised-coordinate layer"><p role="status" className="text-sm text-[#63788b]">Checking the governed coordinate register…</p></MapPanel></>;
  if (coordinates.isError) return <><MapHeader /><MapPanel title="Coordinate register unavailable"><div role="alert" className="rounded-lg border border-[#e5c8c4] bg-[#fff7f5] p-4 text-sm text-[#8b4b45]">The governed coordinate register could not be loaded, so no project markers are being shown. <button onClick={() => coordinates.refetch()} className="font-semibold underline">Retry</button></div></MapPanel></>;
  const activeCoordinates = coordinates.data?.filter(record => Number.isFinite(Number(record.latitude)) && Number.isFinite(Number(record.longitude))) ?? [];
  const hasCoordinates = activeCoordinates.length > 0;
  return <><MapHeader /><MapPanel title="Authorised-coordinate layer"><div className="relative h-[430px] overflow-hidden rounded-xl border border-[#cddbdc] bg-[#e8efec]"><MapContainer center={hasCoordinates ? [Number(activeCoordinates[0].latitude), Number(activeCoordinates[0].longitude)] : [22.8, 79.5]} zoom={hasCoordinates ? 6 : 4.2} minZoom={3.5} maxZoom={9} scrollWheelZoom={false} className="h-full w-full" aria-label={hasCoordinates ? "Authorised project coordinate layer" : "Base map with no authorised project coordinate layer"}><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{activeCoordinates.map(record => <Marker key={record.id} position={[Number(record.latitude), Number(record.longitude)]}><LeafletTooltip direction="top" offset={[0, -10]}><strong>{record.projectId}</strong><br />Authorised {record.precision}-level coordinate</LeafletTooltip></Marker>)}</MapContainer>{!hasCoordinates ? <div className="absolute inset-0 z-[500] grid place-items-center bg-[#102f3b]/22 p-5"><div role="status" className="max-w-lg rounded-xl border border-white/70 bg-[#f9fbf8]/95 p-6 text-center shadow-[0_20px_55px_rgba(18,53,62,0.20)] backdrop-blur-sm"><ShieldCheck className="mx-auto size-7 text-[#147b77]" /><p className="mt-3 text-sm font-semibold text-[#163b45]">No authorised project coordinates are available in this managed demonstration.</p><p className="mt-2 text-xs leading-5 text-[#506a71]">PAIMANA does not infer, substitute, or display synthetic state-centroid project positions on this operational map. An authorised administrator must provide governed coordinate records before a project layer can be enabled.</p></div></div> : null}</div></MapPanel><div className="mt-6 grid gap-5 lg:grid-cols-3"><MapPanel title="Current posture"><p className="text-sm leading-6 text-[#526b74]">{hasCoordinates ? `${activeCoordinates.length} active authorised coordinate record${activeCoordinates.length === 1 ? " is" : "s are"} displayed.` : "Base geography is available for orientation only. The project layer is deliberately withheld."}</p></MapPanel><MapPanel title="Required provenance"><p className="text-sm leading-6 text-[#526b74]">Coordinate source, authority, validation state, and access scope must be recorded before spatial analysis.</p></MapPanel><MapPanel title="Next governed step"><p className="text-sm leading-6 text-[#526b74]">An administrator can use the approved coordinate-intake workflow to publish an authenticated record and supersede obsolete locations.</p></MapPanel></div></>;
}
